### ISSUE TITLE
Editor saves state with every type or every formatting Action

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#189]
this reduces performance immensly!
Also the console.logs etc

**Comment by frogg** [comment]
Yeah! We should definitely remove all console.logs.
It's ok for debugging but don't push it.

I like the focus on performance here, I think it's crucial. There's probably a lot going wrong with the state handling in the editor because that was one of the first components that we developed…without fully understanding the React workflow.

**Comment by dlrenz** [comment]
the best way would be to 
1) define a global variable that defines if we are in dev mode or not. if it is true, have a lot of output on the console everywhere, else have no output
2) in the onChange function just dont do anything, if the last change happened less than x seconds ago

**Comment by dlrenz** [comment]
This is apparently not an issue, the quill onchange doesnt really slow down anything - that problem had to do with thumbnail rendering
