### ISSUE TITLE
Contents cannot be identified by title, but need to have an id

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#229]
When I change only the title of my content, but nothing else in the editor, it is saved as a new content to the backend! apparently the backend uniquely identifies a content by its TITLE?????

**Comment by frogg** [comment]
@dlrenz yes I think you're right. I had similar issues before (where I remixed my own content but the old one was actually overwritten)…

**Comment by dlrenz** [comment]
OK then I think it is best to have unique identifier for contents, as well as slides?

**Comment by frogg** [comment]
👍
Yeah that’s what we had in the original spec anyway.

**Comment by RobZuazua** [comment]
proposed solution: 

1) User saves content first time: username + title combo is unique(which will still be a requirement), the backend will add entry to database with a uniqueId and return uniqueID which will be saved in state. 
2)on open or remix or continued saving, use uniqueId and username to update title/content 
3)we currently grab our (title+ userid) from the url and use that to get&post rates&comments. If titles can change, then we would have to do a fetch call to backend with username and title to get the uniqueId associated with them then do rate/comment with that uniqueContentID.
4) Same goes for analytics and same foes for Get requests.

I am halfway done with this refactor. It is taking a longish time because there are a lot of things to change. Before I commit these changes (which could come with bugs since there are so many changes) I want yall to make sure this makes sense. If it makes sense, I can finish it Monday.

**Comment by dlrenz** [comment]
I think this is good except that I would use the content's uid instead of its title in the URL. 
Then we do not need the fetch call, and also no username on the URL.
