### ISSUE TITLE
analytics crashes when accesstimes array is null

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#262]
<img width="601" alt="screen shot 2018-07-31 at 5 26 40 pm" src="https://user-images.githubusercontent.com/8992275/43490606-fea40d26-94e6-11e8-8d30-35dbdf7e1ee9.png">
<img width="769" alt="screen shot 2018-07-31 at 5 26 32 pm" src="https://user-images.githubusercontent.com/8992275/43490607-febb1b74-94e6-11e8-9174-31577ce016b6.png">

**Comment by dlrenz** [comment]
Hm ok true that is a bug - but how is it possible that accessTimes is empty?
When I click on a content, I open the first slide, so the first time my access to that content is saved to the backend, accessTimes should already be non-empty.

It's probably because timing is stored in the component's state, which is updated asynchronously, so sometimes, the update has not finished before the first API call is made. But timing should not be stored in the state array anyways - this will be one of the upcoming architectural changes (store as little in state as possible)

**Comment by dlrenz** [comment]
can you check if this is fixed now? I set a default behavior for reduce()

**Comment by RobZuazua** [comment]
great!
